### ISSUE TITLE
Strange behaviour when adding a column

### ISSUE THREAD

**Issue by JSKenyon** [ska-sa/dask-ms#165]
* dask-ms version: master
* Python version: 3.8.9
* Operating System:

### Description

When writing to a new column (possibly only when using `taql_where`), there are warnings about inconsistent dimensions. This is strange as the input to the write call has consistent row dimensions (verified in `pdb` just before the `xds_to_table` call). As per our discussion, it looks like the consistency check may be being applied across datasets. 

### What I Did

```
2021-07-08 11:58:45 | WARNING | ms:descriptor | Unable to determine fixed column shapes as input variable dimension sizes are inconsistent
Traceback (most recent call last):

  File "/home/kenyon/venvs/qcenv/bin/goquartical", line 33, in <module>
    sys.exit(load_entry_point('quartical', 'console_scripts', 'goquartical')())
    │   │    └ <function importlib_load_entry_point at 0x7fe230e471f0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/home/kenyon/QuartiCal/quartical/executor.py", line 25, in execute
    _execute(stack)
    │        └ <contextlib.ExitStack object at 0x7fe230d36550>
    └ <function _execute at 0x7fe0ca696700>

  File "/home/kenyon/QuartiCal/quartical/executor.py", line 109, in _execute
    ms_writes = write_xds_list(data_xds_list,
                │              └ [<xarray.Dataset>
                │                Dimensions:              (ant: 58, chan: 4096, corr: 2, dir: 1, row: 85956, uvw: 3)
                │                Coordinates:
                │                    ROWID ...
                └ <function write_xds_list at 0x7fe0d1f65b80>

  File "/home/kenyon/QuartiCal/quartical/data_handling/ms_handler.py", line 233, in write_xds_list
    write_xds_list = xds_to_table(xds_list, ms_path, columns=output_cols)
                     │            │         │                └ ('FLAG_ROW', 'FLAG', 'RANDOM_COL2')
                     │            │         └ '1557347448_J1939_6342_scan1and3.ms'
                     │            └ [<xarray.Dataset>
                     │              Dimensions:              (ant: 58, chan: 4096, corr: 4, dir: 1, row: 85956, uvw: 3)
                     │              Coordinates:
                     │                * corr  ...
                     └ <function xds_to_table at 0x7fe186756040>

  File "/home/kenyon/venvs/qcenv/lib/python3.8/site-packages/daskms/dask_ms.py", line 83, in xds_to_table
    out_ds = write_datasets(table_name, xds, columns,
             │              │           │    └ ('FLAG_ROW', 'FLAG', 'RANDOM_COL2')
             │              │           └ [<xarray.Dataset>
             │              │             Dimensions:              (ant: 58, chan: 4096, corr: 4, dir: 1, row: 85956, uvw: 3)
             │              │             Coordinates:
             │              │               * corr  ...
             │              └ '1557347448_J1939_6342_scan1and3.ms'
             └ <function write_datasets at 0x7fe177c4d280>
  File "/home/kenyon/venvs/qcenv/lib/python3.8/site-packages/daskms/writes.py", line 720, in write_datasets
    tp = _updated_table(table, datasets, columns, descriptor)
         │              │      │         │        └ None
         │              │      │         └ ('FLAG_ROW', 'FLAG', 'RANDOM_COL2')
         │              │      └ [<xarray.Dataset>
         │              │        Dimensions:              (ant: 58, chan: 4096, corr: 4, dir: 1, row: 85956, uvw: 3)
         │              │        Coordinates:
         │              │          * corr  ...
         │              └ '1557347448_J1939_6342_scan1and3.ms'
         └ <function _updated_table at 0x7fe177c49e50>
  File "/home/kenyon/venvs/qcenv/lib/python3.8/site-packages/daskms/writes.py", line 312, in _updated_table
    table_desc = builder.descriptor(variables, default_desc)
                 │       │          │          └ {'UVW': {'valueType': 'double', 'dataManagerType': 'StandardStMan', 'dataManagerGroup': 'StandardStMan', 'option': 5, 'maxlen...
                 │       │          └ defaultdict(<class 'list'>, {'RANDOM_COL2': [<daskms.dataset_schema.ColumnSchema object at 0x7fe226f6bef0>, <daskms.dataset_s...
                 │       └ <function MSDescriptorBuilder.descriptor at 0x7fe226f6d790>
                 └ <daskms.descriptors.ms.MSDescriptorBuilder object at 0x7fe0c852c550>
  File "/home/kenyon/venvs/qcenv/lib/python3.8/site-packages/daskms/descriptors/ms.py", line 103, in descriptor
    ms_dims = self.infer_ms_dims(column_schemas)
              │    │             └ defaultdict(<class 'list'>, {'RANDOM_COL2': [<daskms.dataset_schema.ColumnSchema object at 0x7fe226f6bef0>, <daskms.dataset_s...
              │    └ <staticmethod object at 0x7fe226f4b280>
              └ <daskms.descriptors.ms.MSDescriptorBuilder object at 0x7fe0c852c550>
> File "/home/kenyon/venvs/qcenv/lib/python3.8/site-packages/daskms/descriptors/ms.py", line 117, in infer_ms_dims
    dim_sizes = data_var_dims(expanded_vars)
                │             └ {('RANDOM_COL2', 0): <daskms.dataset_schema.ColumnSchema object at 0x7fe226f6bef0>, ('RANDOM_COL2', 1): <daskms.dataset_schem...
                └ <function data_var_dims at 0x7fe1805cf160>
  File "/home/kenyon/venvs/qcenv/lib/python3.8/site-packages/daskms/dataset.py", line 36, in data_var_dims
    raise DimensionInferenceError("Existing dimension size %s for "
          └ <class 'daskms.dataset.DimensionInferenceError'>

daskms.dataset.DimensionInferenceError: Existing dimension size 87609 for dimension 'row' is inconsistent with same dimension 85956 of array ('RANDOM_COL2', 1)
```

**Comment by ulricharmel** [comment]
I just got the same error with the robust weights @JSKenyon.
